name: HandKnit.Life
favicon: null
layout_spectrum: 0.5
typography_spectrum: 0.49688
title: 'Talking about life, one stitch at a time.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f3f3f3'
    - '#0b0b0b'
    - '#797689'
    - '#454553'
    - '#c8c8c8'
  brandStrength: 1
  lightness: 0.027686033863574266
  saturation: 0.29349706997163594
  rhythmicContrast: 0.5881206328049302
purpose: []
