name: HandKnit.Life
favicon: null
layout_spectrum: 0.5
typography_spectrum: 0.49688
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffbfa'
    - '#a09a9a'
    - '#070707'
    - '#393738'
    - '#d6dcde'
  brandStrength: 0.8473703330382705
  lightness: 0.027686033863574266
  saturation: 0.29349706997163594
  rhythmicContrast: 0.5881206328049302
purpose: []
